/******************************************************************************
 * This file is auto-generated by Vaadin.
 * If you want to customize the entry point, you can copy this file or create
 * your own `index.tsx` in your frontend directory.
 * By default, the `index.tsx` file should be in `./frontend/` folder.
 *
 * NOTE:
 *     - You need to restart the dev-server after adding the new `index.tsx` file.
 *       After that, all modifications to `index.tsx` are recompiled automatically.
 *     - `index.js` is also supported if you don't want to use TypeScript.
 ******************************************************************************/

import { createElement } from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider } from 'react-router';
import { router } from 'Frontend/generated/routes.js';
import {ThemeProvider} from "@/components/theme/ThemeProvider";
import {Toaster} from "@/components/ui/sonner";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ConfirmDialogProvider } from '@/contexts/ConfirmDialogContext';

// Configuration du QueryClient
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            staleTime: 1000 * 60 * 5, // Les données sont considérées fraîches pendant 5 minutes
            gcTime: 1000 * 60 * 30, // Cache conservé 30 minutes (anciennement cacheTime)
            retry: 1, // Réessayer une fois en cas d'erreur
            refetchOnWindowFocus: false, // Ne pas refetch automatiquement au focus de la fenêtre
        },
    },
});

function App() {
    return (
        <QueryClientProvider client={queryClient}>
            <ConfirmDialogProvider>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <RouterProvider router={router} />
                    <Toaster />
                </ThemeProvider>
            </ConfirmDialogProvider>
        </QueryClientProvider>
    );
}

const outlet = document.getElementById('outlet')!;
let root = (outlet as any)._root ?? createRoot(outlet);
(outlet as any)._root = root;
root.render(createElement(App));