name: AuthServer - Release - Build and push Docker image

on:
  push:
    tags:
      - 'v*' # Se déclenche sur les tags type v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Metadata
        id: meta
        run: |
          VERSION=${GITHUB_REF_NAME}
          SHA=$(git rev-parse --short HEAD)
          echo "tag=${VERSION}-${SHA}" >> $GITHUB_OUTPUT

      # Connexion au Tailscale pour accéder au registre privé
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_URL }}/auth-server:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKER_REGISTRY_URL }}/auth-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Kubernetes
            git pull
            cd helm/auth-server
            helm upgrade --install auth-server . --set image.tag=${{ needs.build-and-push.outputs.tag }} --rollback-on-failure --timeout 3m